<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../views/resource/css/style.css">
    <title>Otto Full Stack Test</title>
</head>
<body>
    <div class="top-menu">
        <div class="logo">Otto Store</div>
        <ul class="menu">
            <li><a href="?fetch=<?=$menuParam[0]?>">Index</a></li>
            <li><a href="?fetch=<?=$menuParam[1]?>">Director</a></li>
            <li><a href="?fetch=<?=$menuParam[2]?>&id=1">Single Director</a></li>
            <li><a href="?fetch=<?=$menuParam[3]?>">Business</a></li>
            <li><a href="?fetch=<?=$menuParam[4]?>&id=1">Single Business</a></li>
            <li><a href="?fetch=<?=$menuParam[5]?>&id=1989">Businesses Registered Year</a></li>
            <li><a href="?fetch=<?=$menuParam[6]?>">Last 100</a></li>
            <li><a href="?fetch=<?=$menuParam[7]?>">Business With Director</a></li>
        </ul>
        <div class="search">&nbsp;</div>
    </div>