<div class="container">
    <h1><?php echo ucfirst($requestParam); ?> Listing</h1>
        
    <div class="controls">
    </div>
         
    <table id="productTable" class="product-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Business Name</th>
                <th>Business Address</th>
                <th>Business Registration Date</th>
                <th>Business Registration #</th>
            </tr>
        </thead>
        <tbody id="productTableBody">
            <!-- Table rows will be added here dynamically -->
        </tbody>
    </table>
</div>